### ISSUE TITLE
NTR for underwater noise or sound recording

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/C77#2]
We have received the following request for a new C77 term: 
"I need some advice on what term to register for a Hydrophone instruments in the CSR. I did not find a C77 term for this.
The instrument is recording “underwater sounds”/”ocean sounds” when being towed by a sailing vessel. Any suggestions?"

**Comment by gwemon** [comment]
Proposal to add:
"Underwater sound recording" defined as: "Shipboard activity identifying the recording of underwater sounds or noises using any kind of sound recording equipment."

**Comment by roy-lowry** [comment]
Maybe make the preferred label 'underwater passive acoustics'?

**Comment by danibodc** [comment]
1 new C77 term loaded, it will be live on the NVS from tomorrow morning:

R04 - Underwater passive acoustics

**Comment by danibodc** [comment]
https://vocab.nerc.ac.uk/collection/C77/current/R04/
